version: 2
updates:
  # Enable version updates for Bun dependencies
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
